### ISSUE TITLE
Seite 53 IPv6 

### ISSUE THREAD

**Issue by Hallo-Josh** [xmender/datkombible#9]
"größerer Adressraum (4fach mehr als IPv4)"

Korrekt abgeschrieben von der Bibel, leider trotzdem nicht richtig :)

2^32 = 4,3x10^9
2^128 = 3,4x10^38

**Comment by Hallo-Josh** [comment]
Korrekt wäre: Ungefähr 7.9x10^28fach mehr als IPv4

**Comment by Hallo-Josh** [comment]
Oder 4 Mal so viele Bits zur Adressierung

**Comment by Hallo-Josh** [comment]
"aufgrund des immer größer werdenden Mangels an IPv6-Adressen"
Tipp Fehler -> IPv4-Adressen

**Comment by Hallo-Josh** [comment]
Seite 54 IPv6 -> Adressen
Original: "4x mehr Adressräume als bei IPv4 (2^32 vs. 2^128)"
auch hier "4x mehr Adressbits als bei IPv4 (2^32 vs. 2^128)"

Seite 54 IPv6 -> Länge der Payload
Original: "Länger der Nutzlast"
"Länge der Nutzlast"

**Comment by Hallo-Josh** [comment]
Seite 57 Staufenstermechanismus -> dynamischer Fenstermechanismus
"Fenstegrgröße W auslesen;"

**Comment by xmender** [comment]
alles gefixt, vielen dank!
